"""create test items tables

Revision ID: 47c29737c8dc
Revises: 94e991fbbd24
Create Date: 2026-01-24 23:53:32.835191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c29737c8dc'
down_revision: Union[str, Sequence[str], None] = '94e991fbbd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_items_id'), 'test_items', ['id'], unique=False)
    op.create_index(op.f('ix_test_items_name'), 'test_items', ['name'], unique=False)
    op.create_table('test_items3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_items3_id'), 'test_items3', ['id'], unique=False)
    op.create_index(op.f('ix_test_items3_name'), 'test_items3', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_items3_name'), table_name='test_items3')
    op.drop_index(op.f('ix_test_items3_id'), table_name='test_items3')
    op.drop_table('test_items3')
    op.drop_index(op.f('ix_test_items_name'), table_name='test_items')
    op.drop_index(op.f('ix_test_items_id'), table_name='test_items')
    op.drop_table('test_items')
    # ### end Alembic commands ###
